name: "CI"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install_dependencies]

    steps:
      - uses: wyvox/action@v1
      - name: Lints
        run: pnpm lint

  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: "Tests"
    runs-on: "${{ matrix.platform }}"
    needs: [install_dependencies]

    steps:
    - uses: wyvox/action@v1
    - name: Tests
      run: pnpm test
